version: '2'
services:
  rainloop:
    container_name: rainloop
    image: hardware/rainloop
    restart: always
    volumes:
    - rainloop_data:/rainloop/maildata
    - rainloop_config:/rainloop/data 
    environment:
    - LOG_TO_STDOUT=true
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt:/etc/letsencrypt 
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt 
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
  entry:
    container_name: entry
    image: abiosoft/caddy:0.10.4
    restart: always
    privileged: true
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./entry/Caddyfile:/etc/Caddyfile
    - caddy_data:/root/.caddy
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local 
  rainloop_data:
    driver: local
  rainloop_config:
    driver: local 
  caddy_data:
    driver: local 
